;; Core JS Template
;; source by: Mr. Squally
;; ===========================================================================|
;; Namespace Declaration
(ns personal-site.core
  (:require
   [accountant.core :as accountant]
   [clerk.core :as clerk]
   [reagent.core :as reagent :refer [atom]]
   [reagent.dom :as rdom]
   [reagent.session :as session]
   [reitit.frontend :as reitit]
   [personal-site.routes.about :as about]
   [personal-site.routes.blog :as blog]
   [personal-site.routes.home :as home]
   [personal-site.routes.projects :as projects]
   [personal-site.routes.resume :as resume]))

;; ===========================================================================|
;; Routes
(def router
  (reitit/router
   [["/" :index]
    ["/about" :about]
    ["/blog" :blog]
    ["/projects" :projects]
    ["/resume" :resume]]))

(defn path-for
  [route & [params]]
  (if params
    (:path (reitit/match-by-name router route params))
    (:path (reitit/match-by-name router route))))

;; ===========================================================================|
;; Page components

(defn home-page []
  (fn []
    [:span.main
     [home/page-header]
     [home/page-content]]))

(defn about-page []
  (fn []
    [:span.main
     [about/page-header]
     [about/page-content]]))

(defn blog-page []
  (fn []
    [:span.main
     [blog/page-header]
     [blog/page-content]]))

(defn projects-page []
  (fn []
    [:span.main
     [projects/page-header]
     [projects/page-content]]))

(defn resume-page []
  (fn []
    [:span.main
     [resume/page-header]
     [resume/page-content]]))

;; ===========================================================================|
;; Translate routes -> page components

(defn page-for [route]
  (case route
    :index #'home-page
    :about #'about-page
    :blog #'blog-page
    :projects #'projects-page
    :resume #'resume-page))

;; ===========================================================================|
;; Page mounting component

(defn current-page []
  (fn []
    (let [page (:current-page (session/get :route))]
      [:div
       [:div
        [:img {:src "images/banner.png" :width "100%"}]
        [:span
         [:h6 "Mr. Squally"]
         [:a {:href "mailto:dpcahill98@gmail.com"} [:img {:src "images/logos/gmail.png" :width 30 :height 30}]]
         [:a {:href "https://github.com/MrSqually"} [:img {:src "images/logos/github.png" :width 30 :height 30}]]
         [:a {:href "https://linkedin.com/in/dean-cahill"} [:img {:src "images/logos/linkedin.png" :width 30 :height 30}]]]]
       [:div
       ;;TODO format header & body
        [:header
         [:div [:a {:href (path-for :index)} "Home"] " | "
          [:a {:href (path-for :about)} "About"] " | "
          [:a {:href (path-for :blog)} "Blog"] " | "
          [:a {:href (path-for :projects)} "Projects"] " | "
          [:a {:href (path-for :resume)} "Resume"]]]
        [:hr]
        [page]
        [:footer
         [:div
          [:p
           "© 2025 - Dean Cahill || "
           "site template generated by "
           [:a {:href "https://github.com/reagent-project/reagent-template"} "Reagent Template"] "."]]]]])))

;; ===========================================================================|
;; Initialize app

(defn mount-root []
  (rdom/render [current-page] (.getElementById js/document "app")))

(defn init! []
  (clerk/initialize!)
  (accountant/configure-navigation!
   {:nav-handler
    (fn [path]
      (let [match (reitit/match-by-path router path)
            current-page (:name (:data  match))
            route-params (:path-params match)]
        (reagent/after-render clerk/after-render!)
        (session/put! :route {:current-page (page-for current-page)
                              :route-params route-params})
        (clerk/navigate-page! path)))
    :path-exists?
    (fn [path]
      (boolean (reitit/match-by-path router path)))})
  (accountant/dispatch-current!)
  (mount-root))

(defn ^:dev/after-load reload! []
  (mount-root))
