;; Core JS Template
;; source by: Mr. Squally
;; ===========================================================================|
;; Namespace Declaration
(ns personal-site.core
  (:require
   [accountant.core :as accountant]
   [clerk.core :as clerk]
   [reagent.core :as reagent :refer [atom]]
   [reagent.dom :as rdom]
   [reagent.session :as session]
   [reitit.frontend :as reitit]
   [personal-site.routes.about :as about]
   [personal-site.routes.blog :as blog]
   [personal-site.routes.contact :as contact]
   [personal-site.routes.home :as home]
   [personal-site.routes.projects :as projects]
   [personal-site.routes.resume :as resume]))

;; ===========================================================================|
;; Routes
(def router
  (reitit/router
   [["/" :index]
    ["/about" :about]
    ["/blog" :blog]
    ["/contact" :contact]
    ["/projects" :projects]
    ["/resume" :resume]]))

(defn path-for
  [route & [params]]
  (if params
    (:path (reitit/match-by-name router route params))
    (:path (reitit/match-by-name router route))))

;; ===========================================================================|
;; Page components

(defn home-page []
  (fn []
    [:span.main
     [home/page-header]
     [home/page-content]]))

(defn about-page []
  (fn []
    [:span.main
     [about/page-header]
     [about/page-content]]))

(defn blog-page []
  (fn []
    [:span.main
     [blog/page-header]
     [blog/page-content]]))

(defn contact-page []
  (fn []
    [:span.main
     [contact/page-header]
     [contact/page-content]]))

(defn projects-page []
  (fn []
    [:span.main
     [projects/page-header]
     [projects/page-content]]))

(defn resume-page []
  (fn []
    [:span.main
     [resume/page-header]
     [resume/page-content]]))

;; ===========================================================================|
;; Translate routes -> page components

(defn page-for [route]
  (case route
    :index #'home-page
    :about #'about-page
    :blog #'blog-page
    :contact #'contact-page
    :projects #'projects-page
    :resume #'resume-page))

;; ===========================================================================|
;; Page mounting component

(defn current-page []
  (fn []
    (let [page (:current-page (session/get :route))]
      [:div
       [:header
        [:p [:a {:href (path-for :index)} "Home"] " | "
         [:a {:href (path-for :about)} "About Me"] " | "
         [:a {:href (path-for :blog)} "Blog"] " | "
         [:a {:href (path-for :contact)} "Contact"] " | "
         [:a {:href (path-for :projects)} "Projects"] " | "
         [:a {:href (path-for :resume)} "Resume"]]]
       [page]
       [:footer
        [:p "Site Generated by "
         [:a {:href "https://github.com/reagent-project/reagent-template"} "Reagent Template"] "."]]])))

;; ===========================================================================|
;; Initialize app

(defn mount-root []
  (rdom/render [current-page] (.getElementById js/document "app")))

(defn init! []
  (clerk/initialize!)
  (accountant/configure-navigation!
   {:nav-handler
    (fn [path]
      (let [match (reitit/match-by-path router path)
            current-page (:name (:data  match))
            route-params (:path-params match)]
        (reagent/after-render clerk/after-render!)
        (session/put! :route {:current-page (page-for current-page)
                              :route-params route-params})
        (clerk/navigate-page! path)))
    :path-exists?
    (fn [path]
      (boolean (reitit/match-by-path router path)))})
  (accountant/dispatch-current!)
  (mount-root))

(defn ^:dev/after-load reload! []
  (mount-root))
